# -*- coding: utf-8 -*-
"""How to Run_Colab Version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D6uSZYVWPa-3ftMmxDVBNxBPQf6C5zHc
"""

# Mount Google Drive ──────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

# Set the data path ───────────────────────────────────────────────
DATA_PATH = "/content/drive/MyDrive/MachineLearning/queue_data_file.xlsx"

# Run the loader ───────────────────────────────────────────────────
import sys
sys.path.insert(0, '/content/drive/MyDrive/MachineLearning')  # so Python finds your src/ folder

from src.data_loader import load_queue_data, print_summary
df_raw, df_model = load_queue_data(DATA_PATH)
print_summary(df_raw, df_model)

# Build features (run this next)
from src.features import build_features, time_split
df_feat = build_features(df_model, df_raw)

# Split (run after Cell 4)
train, val, test = time_split(df_feat)

# Install / confirm xgboost (already in Colab, just in case) ───────
!pip install xgboost -q  # uncomment only if needed

import os
os.makedirs('/content/drive/MyDrive/MachineLearning/outputs', exist_ok=True)

# Train both models ─────────────────────────────────────────────────
from src.models import evaluate_models

clf_pre, clf, reg_pre, reg, metrics = evaluate_models(df_feat)

# Install SHAP ──────────────────────────────────────────────────────
!pip install shap -q

# SHAP analysis ─────────────────────────────────────────────────────
from src.shap_analysis import run_shap_analysis

viability_df = run_shap_analysis(clf_pre, clf, reg_pre, reg, train, val, df_feat)